import { Inter } from 'next/font/google'

import '@/styles/globals.scss'
import AppContextProvider from '@/components/AppContext'
import EventBusProvider from '@/components/EventBusContext'

import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContextProvider>
          <EventBusProvider>{children}</EventBusProvider>
        </AppContextProvider>
      </body>
    </html>
  )
}
